remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
plugins:
- jekyll-remote-theme
- jekyll-feed
- jekyll-sitemap

title: Jake LaCaze
description: Writer based in Dallas-Fort Worth doling out perspective as a service
permalink: /:title