theme: minima
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-seo-tag
- jekyll-feed
- jekyll-sitemap

title: Jake LaCaze
description: Writer based in Dallas-Fort Worth doling out perspective as a service
permalink: pretty